{% set name = "gmwi2" %}
{% set version = "1.2" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  path: ..

requirements:
  host:
    - pip
    - python
  run:
    - python
    - metaphlan=3.0.13
    - pandas
    - scikit-learn=1.2.2
    - halo

test:

about:
  home: https://github.com/danielchang2002/GMWI2
  license: MIT
  license_family: MIT
  summary: Enhanced Health Status Prediction from Gut Microbiome Taxonomic Profiles
